name: Integration

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Remove node_modules and package-lock.json
        run: |
          rm -rf node_modules
          rm bun.lockb

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      # Add this step if you have tests in the future
      # - name: Run tests
      #   run: bun test